name: actionlint

on:
  - push
  - pull_request

jobs:
  actionlint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Update ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          shellcheck -V

      - name: actionlint
        run: |
          curl -fLO --retry 3 --retry-delay 5 \
              "https://github.com/rhysd/actionlint/releases/download/v1.7.12/actionlint_1.7.12_linux_amd64.tar.gz"
          echo "8aca8db96f1b94770f1b0d72b6dddcb1ebb8123cb3712530b08cc387b349a3d8  actionlint_1.7.12_linux_amd64.tar.gz" | sha256sum --check
          tar -xzf actionlint_1.7.12_linux_amd64.tar.gz actionlint
          ./actionlint -color
